POST https://localhost:5001/api/Animal/post
Content-Type: application/json

{
    "Name": "Thor",
    "Breed": "York",
    "CustomerId": 21
}

### get all addresses 
GET https://localhost:5001/api/Animal/getAll


### search by ID 
GET https://localhost:5001/api/Animal/getById/4

### update an existing address by ID 
PUT https://localhost:5001/api/Animal/put/25
Content-Type: application/json

{
    "Name": "nome'",
    "Breed": "raça",
    "CustomerId": 15
}


### deletion of a address by ID
DELETE https://localhost:5001/api/Animal/delete/2