POST https://localhost:5001/api/Animal/post
Content-Type: application/json

{
    "Name": "Gatinha Noturna",
    "Breed": "Black Cat",
    "CustomerId": 3
}

### get all addresses 
GET https://localhost:5001/api/Animal/getAll


### search by ID 
GET https://localhost:5001/api/Animal/getById/4

### update an existing address by ID 
PUT https://localhost:5001/api/Animal/put/1
Content-Type: application/json

{
    "Name": "Animal 1'",
    "Breed": "raça",
    "CustomerId": 1
}


### deletion of a address by ID
DELETE https://localhost:5001/api/Animal/delete/2